version: "3.8"
services:
  redis:
    image: redis:latest
    networks:
      - ingress
    ports:
      - 6379
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  billproservice:
    image: oraio/billproservice:latest
    networks:
      - ingress
    ports:
      - 8000
    env_file:
      - "$PWD/backend/.env"
    volumes:
      - "$PWD/backend/credentials:/usr/src/app/backend/credentials"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        ingress.host: topup.billpro.oraio.tech
        ingress.port: 8000
        ingress.virtual_proto: http
        ingress.ssl: enable
        ingress.ssl_redirect: enable

networks:
  ingress:
    external: true
    name: ingress-routing

volumes:
  redis-data:
    external: true
